# Generated by Django 3.2.4 on 2021-06-16 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedPersonalDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(max_length=45)),
                ('LastName', models.CharField(max_length=45)),
                ('PhoneNumber', models.CharField(max_length=11)),
                ('EmailAddress', models.CharField(max_length=255, unique=True)),
                ('RoomNumber', models.CharField(max_length=5)),
                ('SubjectsTaught', models.CharField(max_length=205)),
                ('Photo', models.CharField(max_length=200)),
            ],
        ),
    ]
